### ISSUE TITLE
Default empty constructor for AmazonS3Client (and others)

### ISSUE THREAD

**Issue by andyscott** [seratch/AWScala#11]
In some circumstances, leveraging the default constructor for the java S3 client is more appealing than the default constructor provided in AWScala.

Both default constructors look for credentials stored in system properties. However, the scala API fails if the parameters aren't present. The java API won't fail. And if you're running the code on an EC2 instance with an IAM role that grants permissions to S3 buckets, you'll be in the clear. See http://blogs.aws.amazon.com/security/post/Tx1XG3FX6VMU6O5/A-safer-way-to-distribute-AWS-credentials-to-EC2

At the moment, this is how I initialize my S3 client.

    val s3 = new AmazonS3Client with S3 {
      override def createBucket(name: String): Bucket = super.createBucket(name)
    }

Can we add more direct support for the default constructors of the underlying java APIs?

**Comment by iceberg901** [comment]
So I've discovered that my fix isn't really a fix.  Even though DefaultAwsCredentialsProviderChain is now used by deafult, awscala grabs the credentials once and then holds them forever.  This doesn't work for IAM roles, because the credentials are regularly invalidated and regenerated, so once this happens once the credentials held by awscala stop working.  I am re-opening and will write a real fix and create a PR.

**Comment by iceberg901** [comment]
From version 0.5.0 onward the default constructors of all clients in AWScala use the DefaultAWSCredentialsProviderChain, which will fallback to IAM role as the last choice in its chain.  They will also automatically refresh IAM role credentials so they don't get stuck with expired ones.
